import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ContactProvider } from "@/components/ContactModal";

const geistMonoHeading = Geist_Mono({subsets:['latin'],variable:'--font-heading'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "jshmslf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, geistMonoHeading.variable)}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: `(function(){var t=localStorage.getItem('theme');if(t==='dark'||(!t&&'${process.env.NEXT_PUBLIC_DEFAULT_THEME||'dark'}'==='dark'))document.documentElement.classList.add('dark')})()` }} />
      </head>
      <body className="min-h-full flex flex-col"><ContactProvider>{children}</ContactProvider></body>
    </html>
  );
}
